# Generated by Django 5.2.7 on 2025-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_paid_amount_invoice_paid_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(default=0)),
                ('max_number', models.PositiveIntegerField(default=10000)),
            ],
            options={
                'verbose_name': 'Invoice Number Tracker',
                'verbose_name_plural': 'Invoice Number Tracker',
            },
        ),
    ]
