# Generated by Django 5.2.7 on 2025-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_notified',
            field=models.BooleanField(default=False),
        ),
    ]
