# Generated by Django 5.2.7 on 2025-11-25 18:23

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Q, Sum


def populate_stock_totals(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    StockTransaction = apps.get_model('inventory', 'StockTransaction')

    aggregates = (
        StockTransaction.objects.values('item')
        .annotate(
            total_in=Sum('quantity', filter=Q(txn_type='IN')),
            total_out=Sum('quantity', filter=Q(txn_type='OUT')),
        )
    )
    aggregate_map = {
        row['item']: {
            'total_in': row['total_in'] or Decimal('0'),
            'total_out': row['total_out'] or Decimal('0'),
        }
        for row in aggregates
    }

    for item in Item.objects.all():
        totals = aggregate_map.get(
            item.id, {'total_in': Decimal('0'), 'total_out': Decimal('0')}
        )
        current = totals['total_in'] - totals['total_out']
        item.total_in_stock = totals['total_in']
        item.total_out_stock = totals['total_out']
        item.current_stock = current
        item.save(update_fields=['total_in_stock', 'total_out_stock', 'current_stock'])


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_low_stock_notified'),
        ('inventory', '0002_alter_stocktransaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='item',
            name='total_in_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='item',
            name='total_out_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.RunPython(
            code=populate_stock_totals,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
