# Generated by Django 5.2.7 on 2025-11-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stocktransaction_id'),
        ('items', '0003_item_current_stock_item_total_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txns', to='items.item'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='txn_type',
            field=models.CharField(choices=[('IN', 'Stock IN'), ('OUT', 'Stock OUT')], max_length=3),
        ),
    ]
